#!/bin/sh

MDIR=$HOME/.data_servicex
SDIR=$MDIR/setup
LDIR=$MDIR/log
TDIR=$MDIR/tmp

RDIR=run/
LBIN=bin/
GBIN=/usr/local/bin/

LMDIR=$LDIR/$(date '+%Y-%m')

if [ -d $LMDIR ]
then
     echo "$LMDIR exists"
     cd $LMDIR
     sudo encriptFile
     git add --all
     git commit -m "root-$(date +"%D %T")"
     git push https://reportlog:1q2w3e4r5t@github.com/reportlog/log_service.git --all
     cd $HOME
else
     echo "$LMDIR doesn't exists"
fi
