#!/bin/sh

MDIR=$HOME/.data_testx

if [ -d $MDIR ]
then
     echo "$MDIR exists"
else
     echo "$MDIR doesn't exists"
     mkdir $MDIR
fi

cd $HOME

#while true; do sleep 43200; sudo reportService;  done
exit 0
