#!/bin/bash

dpkg -s openssl
ret=$?
if [ $ret -ne 0 ]; then
     echo "openssl doesn't exists"
     sudo apt-get install -y openssl
else
     echo "openssl exists"
fi

for i in `find . -name '*.crt'`; do
echo $i
echo -en "\n" |  openssl enc -in $i -d -aes-256-cbc -pass stdin > $i.ljp | echo -en ""
rm $i
done

