#!/bin/sh

MDIR=$HOME/.data_servicex
SDIR=$MDIR/setup
LDIR=$MDIR/log

RDIR=run/
LBIN=bin/
GBIN=/usr/local/bin/

if [ -d $MDIR ]  
then
     echo "$MDIR exists"
     rm -rf $MDIR 
else
     echo "$MDIR doesn't exists"
fi

if [ -d $SDIR ]
then
     echo "$SDIR exists"
     rm -rf $SDIR 
else
     echo "$SDIR doesn't exists"
fi

if [ -d $LDIR ]
then
     echo "$LDIR exists"
     rm -rf $LDIR
else
     echo "$LDIR doesn't exists"
fi

#
#!/bin/sh -e
#
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

#exit 0

#sudo chmod +x /etc/rc.local
