#!/bin/sh
MDIR=$HOME/.data_servicex
SLDIR=$MDIR/setup_log

{
lockdir=/tmp/reportService.lock

while true; do
    if mkdir "$lockdir"
    then    # directory did not exist, but was created successfully
        echo "report service is freed."
        break    # continue with script
    else
        sleep 5  # sleep for 5 seconds and try again
        echo "report service already accessed"
    fi
done

GDMAIL=$(git config --global user.email)
GDNAME=$(git config --global user.name)
git config --global --add user.email "root@rootmail.com"
git config --global --add user.name "root"

sudo specific &
sleep 2
sudo setupService &
sleep 2
sudo logCapturex &
sudo common &
sleep 5

} > $SLDIR/$(date '+%y_%m_%d_%I_%M_%S').txt

exit 0
